// LOGIN
export const LOGIN = 'LOGIN';
export const RECORD = 'RECORD';
export const ADDUSERFORM = 'ADDUSERFORM';
export const ADDLEADTOUSERFORM = 'ADDLEADTOUSERFORM';
export const ADDCONSULTANTTOUSERFORM = 'ADDCONSULTANTTOUSERFORM';
export const ADDCOMPANIESTOUSERFORM = 'ADDCOMPANIESTOUSERFORM';
export const GETUSERBYIDROWDATA = 'GETUSERBYIDROWDATA';
